### ISSUE TITLE
Implement prompt “…” contextual menu (to remove prompt, jump to source)

### ISSUE THREAD

**Issue by andymatuschak** [andymatuschak/orbit-summer-2022-demo#28]
In floating / bulk prompts:
- "Unsave Prompt" (for author prompts) / "Delete Prompt" (for yours)

In prompt list module:
- "Unsave Prompt" (for author prompts) / "Delete Prompt" (for yours)
- "Jump to Source Location" (don't like this wording but struggling to improve—work on this a little more)

**Comment by andymatuschak** [comment]
(Where does the contextual menu go in collapsed prompts? Will be more disruptive if it's mirrored to the left corner. Try below the Orbit icon? That didn't work for the normal layout, but maybe it'll work here…)

**Comment by HammadB** [comment]
13fdff41d78e17ccc1218dda03ad6d0aed7a2342 Completes this with the exception of collapsed.

**Comment by andymatuschak** [comment]
Looking really great!

**Comment by andymatuschak** [comment]
@HammadB For the right-to-left collapsed state menu layout, let's roll with:

![image](https://user-images.githubusercontent.com/2771/192026596-73ee17cf-0af4-4e0d-a74c-18a1a627e9f9.png)

I'm not thrilled with this, but I think it's the right simple approach for this round of prototyping.

I find myself increasingly wanting to replace the "…" with a simple "X" for floating prompts. Then I'd use a "…" menu instead of the "X" in the prompt list case, where there are multiple actions. But in the prompt list, there's no collapsed state, so no need to handle this edge case.

**Comment by HammadB** [comment]
Agree on replacing ellipses with X when there is only one option. Making undo of the action cheaper would be nice.

**Comment by andymatuschak** [comment]
Assigning to me to implement collapsed positioning.

**Comment by HammadB** [comment]
I got some bandwidth to do this!
