### ISSUE TITLE
Implement bulk collapsed state

### ISSUE THREAD

**Issue by andymatuschak** [andymatuschak/orbit-summer-2022-demo#36]
Will sketch this then pass to you, @HammadB!

**Comment by andymatuschak** [comment]
Three concepts (https://www.figma.com/file/EeIDP8mQ2fYgEkGhapF5bu/Orbit---Summer-2022-Prototype?node-id=271%3A19331):

![image](https://user-images.githubusercontent.com/2771/191322720-d205a501-3d55-4d7c-a2cf-ed12457bb129.png)

I think the third concept works best, but to avoid invasive changes, I'd suggest we go with the first. What do you think, @HammadB?

**Comment by HammadB** [comment]
closed by #81
