### ISSUE TITLE
Implement repeated starburst icon affordance for bulk prompt (idle state)

### ISSUE THREAD

**Issue by andymatuschak** [andymatuschak/orbit-summer-2022-demo#39]
<img width="285" alt="image" src="https://user-images.githubusercontent.com/2771/191303847-9904e942-1220-403a-8b87-7421c18f87c2.png">

**Comment by HammadB** [comment]
We discussed offline leaving it out, but perhaps misunderstood. We can put it in - the offline context was what N to cap this at / whats the logic for how many to show?

**Comment by andymatuschak** [comment]
Ah, yeah, I'd still like it—I was unclear!

You asked "Assuming we want to cut off the repetition at some N?"; my response: "Suggest we not worry about it for the moment: the rest of the interaction/presentation won’t work well for more than 6 anyway."

By "let's not worry", I meant about a cap or cut-off, since I don't think that edge case will be meaningful for the proto (I'll have to design some alternative state for that case later). We can just naively duplicate—one starburst for each prompt in the bulk item!

**Comment by HammadB** [comment]
Cool - on it.
