### ISSUE TITLE
Add suggested prompt 

### ISSUE THREAD

**Issue by HammadB** [andymatuschak/orbit-summer-2022-demo#46]
When highlighting, if your range intersects an existing range, then we need to show add suggested prompts in the context menu

**Comment by andymatuschak** [comment]
https://user-images.githubusercontent.com/2771/191803260-f959be4f-3b08-4f37-b0c0-139a5c4c3d59.mov

**Comment by andymatuschak** [comment]
Tracking edge case for bulk prompts: [andymatuschak/orbit-summer-2022-demo#73 Implement suggested prompt presentation state for bulk prompts]
