### ISSUE TITLE
Highlight all associated anchors when hovering bulk prompt save button

### ISSUE THREAD

**Issue by andymatuschak** [andymatuschak/orbit-summer-2022-demo#49]
See 12:10: https://youtu.be/LRUWdwGZuLA?t=730

Right now, we only highlight the first prompt's anchor when the bulk save button is hovered.

**Comment by HammadB** [comment]
Progress by #56 

Two edge cases remain for hovering:

We split a bulk prompt with shared anchors and then highlight its children (what happens when we highlight the anchor then?)
We are in a bulk prompt hover, start editing, and then hover off. The edit anchor highlight should be preserved but
